version: '3'

services:
  backend:
    build: .
    container_name: backend
    expose:
      - 8081
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker.internal.host:3306
    depends_on:
      - mysql